version:  '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-micro
      MYSQL_USER: micro
      MYSQL_PASSWORD: micro
    ports:
    - 3306:3306
  jaeger:
    image: jaegertracing/all-in-one:1.18
    ports:
        - "16686:16686"

  user-server:
    depends_on:
      - db
    build: ./user-srv
    environment:
      GO_MICRO_DB_HOST: db:3306
      GO_MICRO_DB_USER: micro
      GO_MICRO_DB_PASSWORD: micro
      GO_MICRO_DB_NAME: go-micro
      JAEGER_AGENT_HOST: jaeger:6831

  api-server:
    depends_on:
      - db
      - user-server
    build: ./api
    ports:
    - 8080:8080
    environment:
      USER_GRPC_HOST: user-server:50050
      JAEGER_AGENT_HOST: jaeger:6831

  etcd1:
    image: quay.io/coreos/etcd
    container_name: etcd1
    command: etcd -name etcd1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - 2379
      - 2380

  etcd2:
    image: quay.io/coreos/etcd
    container_name: etcd2
    command: etcd -name etcd2 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - 2379
      - 2380

  etcd3:
    image: quay.io/coreos/etcd
    container_name: etcd3
    command: etcd -name etcd3 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - 2379
      - 2380

volumes:
  db_data: {}