version:  '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-micro
      MYSQL_USER: micro
      MYSQL_PASSWORD: micro
    ports:
    - 3306:3306
  jaeger:
    image: jaegertracing/all-in-one:1.18
    ports:
        - "16686:16686"

  user-server:
    depends_on:
      - db
    build: ./user-srv
    environment:
      GO_MICRO_DB_HOST: db:3306
      GO_MICRO_DB_USER: micro
      GO_MICRO_DB_PASSWORD: micro
      GO_MICRO_DB_NAME: go-micro
      JAEGER_AGENT_HOST: jaeger:6831

  api-server:
    depends_on:
      - db
      - user-server
    build: ./api
    ports:
    - 8080:8080
    environment:
      USER_GRPC_HOST: user-server:50050
      JAEGER_AGENT_HOST: jaeger:6831

volumes:
  db_data: {}